/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.cmpe202.hotels.api;

import com.cmpe202.hotels.model.ReservationInfo;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.List;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-22T20:24:30.862902-07:00[America/Los_Angeles]")
@Api(value = "reservation", description = "the reservation API")
public interface ReservationApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /reservation/{accountId} : Fetches reservations for an account.
     * Fetches reservations for an account.
     *
     * @param accountId accountId (required)
     * @return Returns list of reservations for an account. (status code 200)
     *         or bad input parameter (status code 400)
     */
    @ApiOperation(value = "Fetches reservations for an account.", nickname = "getReservationsForAnAccount", notes = "Fetches reservations for an account.", response = ReservationInfo.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns list of reservations for an account.", response = ReservationInfo.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @GetMapping(
        value = "/reservation/{accountId}",
        produces = "application/json"
    )
    default ResponseEntity<List<ReservationInfo>> getReservationsForAnAccount(@ApiParam(value = "accountId",required=true) @PathVariable("accountId") String accountId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accountId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"hotelInfo\" : { \"zipcode\" : \"zipcode\", \"rooms\" : [ { \"roomId\" : \"d290f1ee-6c54-4b01-90e6-d701748f0851\", \"roomPhotoUrl\" : \"roomPhotoUrl\", \"roomFeatures\" : [ \"roomFeatures\", \"roomFeatures\" ], \"basePrice\" : 0.8008281904610115 }, { \"roomId\" : \"d290f1ee-6c54-4b01-90e6-d701748f0851\", \"roomPhotoUrl\" : \"roomPhotoUrl\", \"roomFeatures\" : [ \"roomFeatures\", \"roomFeatures\" ], \"basePrice\" : 0.8008281904610115 } ], \"address\" : \"address\", \"name\" : \"Any acceptable name of the hotel\", \"hotelId\" : \"d290f1ee-6c54-4b01-90e6-d701748f0851\" }, \"reservationId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"hotelId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"roomId\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"roomInfo\" : { \"roomId\" : \"d290f1ee-6c54-4b01-90e6-d701748f0851\", \"roomPhotoUrl\" : \"roomPhotoUrl\", \"roomFeatures\" : [ \"roomFeatures\", \"roomFeatures\" ], \"basePrice\" : 0.8008281904610115 } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
