/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.1.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.cmpe202.hotels.api;

import com.cmpe202.hotels.model.AccountInfo;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;

import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-22T20:24:30.862902-07:00[America/Los_Angeles]")
@Api(value = "account", description = "the account API")
public interface AccountApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /account/{accountId} : Fetches the account details of an account
     * Fetches the account details of an account.
     *
     * @param accountId Pass AccountId to fetch information. (required)
     * @return Returns AccountInfo (status code 200)
     *         or bad input parameter (status code 400)
     */
    @ApiOperation(value = "Fetches the account details of an account", nickname = "getAccountInfo", notes = "Fetches the account details of an account.", response = AccountInfo.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Returns AccountInfo", response = AccountInfo.class),
        @ApiResponse(code = 400, message = "bad input parameter") })
    @GetMapping(
        value = "/account/{accountId}",
        produces = "application/json"
    )
    default ResponseEntity<AccountInfo> getAccountInfo(@ApiParam(value = "Pass AccountId to fetch information.",required=true) @PathVariable("accountId") String accountId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accountId\" : \"d290f1ee-6c54-4b01-90e6-d701748f0851\", \"password\" : \"password\", \"rewardsPoint\" : 230, \"username\" : \"Any acceptable Username\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /account : creates a new account
     * Adds an account into the system.
     *
     * @param accountInfo AccountInfo is returned. (optional)
     * @return item created (status code 201)
     *         or invalid input, object invalid (status code 400)
     *         or an existing item already exists (status code 409)
     */
    @ApiOperation(value = "creates a new account", nickname = "postAccountInfo", notes = "Adds an account into the system.", response = AccountInfo.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "item created", response = AccountInfo.class),
        @ApiResponse(code = 400, message = "invalid input, object invalid"),
        @ApiResponse(code = 409, message = "an existing item already exists") })
    @PostMapping(
        value = "/account",
        produces = "application/json",
        consumes = "application/json"
    )
    default ResponseEntity<AccountInfo> postAccountInfo(@ApiParam(value = "AccountInfo is returned."  )   @RequestBody(required = false) AccountInfo accountInfo) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"accountId\" : \"d290f1ee-6c54-4b01-90e6-d701748f0851\", \"password\" : \"password\", \"rewardsPoint\" : 230, \"username\" : \"Any acceptable Username\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
